- %SF_SYMFONY_LIB_DIR%/view/sfPartialView.class.php
- %SF_ROOT_DIR%/plugins/isoOptimizerPlugin/lib/view/isoPHPView.class.php
- %SF_ROOT_DIR%/plugins/isoOptimizerPlugin/lib/view/isoPartialView.class.php
- %SF_ROOT_DIR%/plugins/isoOptimizerPlugin/lib/view/isoViewParameterHolder.class.php

- %SF_SYMFONY_LIB_DIR%/escaper/sfOutputEscaper.class.php
- %SF_SYMFONY_LIB_DIR%/escaper/sfOutputEscaperGetterDecorator.class.php
- %SF_SYMFONY_LIB_DIR%/escaper/sfOutputEscaperArrayDecorator.class.php
- %SF_SYMFONY_LIB_DIR%/escaper/sfOutputEscaperObjectDecorator.class.php
- %SF_SYMFONY_LIB_DIR%/escaper/sfOutputEscaperIteratorDecorator.class.php
- %SF_ROOT_DIR%/plugins/isoOptimizerPlugin/lib/view/escaper/isoOutputEscaper.class.php
- %SF_ROOT_DIR%/plugins/isoOptimizerPlugin/lib/view/escaper/isoOutputEscaperArrayDecorator.class.php
- %SF_ROOT_DIR%/plugins/isoOptimizerPlugin/lib/view/escaper/isoOutputEscaperIteratorDecorator.class.php
- %SF_ROOT_DIR%/plugins/isoOptimizerPlugin/lib/view/escaper/isoOutputEscaperObjectDecorator.class.php

