user_profile:
    url:   /user/user_profile
    param: { module: user, action: userProfile }

user_list:
    url:   /user/user_list
    param: { module: user, action: userList }

log_in:
    url:   /user/log_in
    param: { module: user, action: logIn }

log_out:
    url:   /user/log_out
    param: { module: user, action: logOut }

registration:
    url:   /user/registration
    param: { module: user, action: registration }

homepage:
  url:   /
  param: { module: user, action: logIn }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
