prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    standard_helpers: [I18N, Partial, Date]
    # Form security secret (CSRF protection)
    # csrf_secret:            7a5fd2d94ef29cfe9ebb48295a87bd4b6d15dc8b

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

  .actions:
    login_module: user
    login_action: logIn

    secure_module: default
    secure_action: secure

    error_404_module: default
    error_404_action: error404
